"""Changed id to string (GUID)

Revision ID: 9e0c1112282b
Revises: 287218361093
Create Date: 2023-05-15 20:19:50.524570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0c1112282b'
down_revision = '287218361093'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
